/**
 * Database Schema Definitions (Drizzle ORM)
 *
 * These define the core authentication tables managed by Better Auth.
 * Additional tables (org, org_members, etc.) are managed via raw SQL migrations
 * since they're not part of the Better Auth schema.
 */

import {
  sqliteTable,
  text,
  integer,
  index,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// =============================================================================
// User Table
// =============================================================================

/**
 * Users - the core user account table.
 *
 * Managed by Better Auth but extended with Docket-specific fields.
 * Users can belong to multiple organizations via org_members.
 */
export const user = sqliteTable(
  "user",
  {
    // Primary key - UUID generated by Better Auth
    id: text("id").primaryKey().notNull(),

    // Display name
    name: text("name").notNull(),

    // Email address (unique across all users)
    email: text("email").notNull(),

    // Whether the email has been verified
    emailVerified: integer("email_verified", { mode: "boolean" })
      .notNull()
      .default(false),

    // Profile image URL (from OAuth providers or uploaded)
    image: text("image"),

    // Timestamps
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [
    // Email must be unique
    uniqueIndex("user_email_unique").on(table.email),
  ]
);

// =============================================================================
// Session Table
// =============================================================================

/**
 * Sessions - active user login sessions.
 *
 * Better Auth manages session lifecycle automatically:
 * - Created on login
 * - Refreshed on activity
 * - Deleted on logout or expiry
 */
export const session = sqliteTable(
  "session",
  {
    // Primary key - UUID
    id: text("id").primaryKey().notNull(),

    // When this session expires
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),

    // Session token (used in cookies)
    token: text("token").notNull(),

    // Timestamps
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),

    // Client info (optional, for audit purposes)
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),

    // Foreign key to user
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [
    // Session token must be unique
    uniqueIndex("session_token_unique").on(table.token),

    // Fast lookup by user (for "logout all sessions")
    index("session_userId_idx").on(table.userId),
  ]
);

// =============================================================================
// Account Table
// =============================================================================

/**
 * Accounts - OAuth provider connections and credentials.
 *
 * Each user can have multiple accounts (Google, Apple, etc).
 * Better Auth handles token refresh automatically.
 */
export const account = sqliteTable(
  "account",
  {
    // Primary key - UUID
    id: text("id").primaryKey().notNull(),

    // The ID from the OAuth provider
    accountId: text("account_id").notNull(),

    // Which provider (google, apple, etc)
    providerId: text("provider_id").notNull(),

    // Foreign key to user
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // OAuth tokens
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),

    // Token expiry timestamps
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),

    // OAuth scope granted
    scope: text("scope"),

    // Password hash (for email/password auth only)
    password: text("password"),

    // Timestamps
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [
    // Fast lookup by user
    index("account_userId_idx").on(table.userId),
  ]
);

// =============================================================================
// Verification Table
// =============================================================================

/**
 * Verification - stores temporary verification tokens.
 *
 * Used for:
 * - Email verification links
 * - Password reset codes
 * - Magic login links
 */
export const verification = sqliteTable(
  "verification",
  {
    // Primary key - UUID
    id: text("id").primaryKey().notNull(),

    // What this verification is for (email address, etc)
    identifier: text("identifier").notNull(),

    // The verification token/code
    value: text("value").notNull(),

    // When this verification expires
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),

    // Timestamps
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [
    // Fast lookup by identifier (email)
    index("verification_identifier_idx").on(table.identifier),
  ]
);
